max_level: 6
redis: 'redis://localhost:6379/0'

api:
  portal: "http://portal"
  uic: "http://uic"

sentry: ''

strategy:
  - name: debug
    provider: debug
    level: '0123456'

  - name: phonecall
    provider: nexmo_tts
    level: '0'
    api_key: 123123123j
    api_secret: 123123123
    voice: female
    lg: zh-cn
    repeat: 3
    prefix: ''

  - name: sms
    provider: yunpian_sms
    level: '012'
    signature: 'LC报警'
    api_key: 123123123

  - name: pagerduty
    provider: pagerduty
    level: '0123'
    api_key: 123123123

  - name: onealert
    provider: onealert
    level: '0123'
    api_key: 123123123

  - name: mail
    provider: smtp
    # omit 0123 since pagerduty has email noti
    level: '4'
    server: smtp.163.com
    send_from: foo@163.com
    username: foo
    password: foo

  - name: bearychat
    provider: bearychat
    level: '012345'

  - name: indicator
    # do nothing, just consume the queue.
    # indicator will poll api
    provider: noop
    level: '0123456'
